- name: runners
  description: All zombies are runners
  points_multiplier: 0.0
  cvars:
    - runners_only 1

- name: no zombie respawning
  description: Spawn brushes do not regenerate zombies
  points_multiplier: 0.0
  cvars:
    - sv_spawn_regen_target 0

- name: sunny
  description: Enforces stage 1 in nmo_tenkinoko_welkin
  points_multiplier: 0.0
  cvars:
    - sm_tenki_stage 1
  maps: 
    - nmo_tenkinoko_welkin_*
  private: 1

- name: cloudy
  description: Enforces stage 2 in nmo_tenkinoko_welkin
  points_multiplier: 2.0
  cvars:
    - sm_tenki_stage 2
  maps: 
    - nmo_tenkinoko_welkin_*
  private: 1